import { EmploymentContract } from "@/types/employment-contract";

export const mockEmploymentContracts: EmploymentContract[] = [
  {
    id: "EC-EMP001",
    employeeId: "EMP001",
    typeOfWorkTh: "พนักงานครัว",
    typeOfWorkEn: "Kitchen Staff",
    incomePerDay: 480,
    payIncomeDate: 30,
    periodOfEmployment: 24,
    workingHourLimit: 8,
    workingDayPerWeek: 6,
    daysOffWeeklyTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffWeeklyEn: "The Labour Protection Law",
    daysOffHolidayTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffHolidayEn: "The Labour Protection Law",
    daysAnnualLeaveTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysAnnualLeaveEn: "The Labour Protection Law",
    overtimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    overtimeRateEn: "The Labour Protection Law",
    holidayOvertimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    holidayOvertimeRateEn: "The Labour Protection Law",
    createdAt: new Date("2023-10-01")
  },
  {
    id: "EC-EMP002",
    employeeId: "EMP002",
    typeOfWorkTh: "พนักงานบริการ",
    typeOfWorkEn: "Service Staff",
    incomePerDay: 450,
    payIncomeDate: 30,
    periodOfEmployment: 18,
    workingHourLimit: 8,
    workingDayPerWeek: 6,
    daysOffWeeklyTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffWeeklyEn: "The Labour Protection Law",
    daysOffHolidayTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffHolidayEn: "The Labour Protection Law",
    daysAnnualLeaveTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysAnnualLeaveEn: "The Labour Protection Law",
    overtimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    overtimeRateEn: "The Labour Protection Law",
    holidayOvertimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    holidayOvertimeRateEn: "The Labour Protection Law",
    createdAt: new Date("2023-11-12")
  },
  {
    id: "EC-EMP003",
    employeeId: "EMP003",
    typeOfWorkTh: "คนงานผลิต",
    typeOfWorkEn: "Production Worker",
    incomePerDay: 420,
    payIncomeDate: 30,
    periodOfEmployment: 12,
    workingHourLimit: 8,
    workingDayPerWeek: 5,
    daysOffWeeklyTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffWeeklyEn: "The Labour Protection Law",
    daysOffHolidayTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffHolidayEn: "The Labour Protection Law",
    daysAnnualLeaveTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysAnnualLeaveEn: "The Labour Protection Law",
    overtimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    overtimeRateEn: "The Labour Protection Law",
    holidayOvertimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    holidayOvertimeRateEn: "The Labour Protection Law",
    createdAt: new Date("2022-08-20")
  },
  {
    id: "EC-EMP004",
    employeeId: "EMP004",
    typeOfWorkTh: "ช่างเทคนิค",
    typeOfWorkEn: "Technician",
    incomePerDay: 520,
    payIncomeDate: 30,
    periodOfEmployment: 36,
    workingHourLimit: 8,
    workingDayPerWeek: 5,
    daysOffWeeklyTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffWeeklyEn: "The Labour Protection Law",
    daysOffHolidayTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffHolidayEn: "The Labour Protection Law",
    daysAnnualLeaveTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysAnnualLeaveEn: "The Labour Protection Law",
    overtimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    overtimeRateEn: "The Labour Protection Law",
    holidayOvertimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    holidayOvertimeRateEn: "The Labour Protection Law",
    createdAt: new Date("2023-02-14")
  },
  {
    id: "EC-EMP005",
    employeeId: "EMP005",
    typeOfWorkTh: "คนงานเกษตร",
    typeOfWorkEn: "Agricultural Worker",
    incomePerDay: 400,
    payIncomeDate: 30,
    periodOfEmployment: 22,
    workingHourLimit: 8,
    workingDayPerWeek: 6,
    daysOffWeeklyTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffWeeklyEn: "The Labour Protection Law",
    daysOffHolidayTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffHolidayEn: "The Labour Protection Law",
    daysAnnualLeaveTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysAnnualLeaveEn: "The Labour Protection Law",
    overtimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    overtimeRateEn: "The Labour Protection Law",
    holidayOvertimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    holidayOvertimeRateEn: "The Labour Protection Law",
    createdAt: new Date("2023-05-09")
  },
  {
    id: "EC-EMP006",
    employeeId: "EMP006",
    typeOfWorkTh: "พนักงานคลังสินค้า",
    typeOfWorkEn: "Warehouse Staff",
    incomePerDay: 430,
    payIncomeDate: 30,
    periodOfEmployment: 27,
    workingHourLimit: 8,
    workingDayPerWeek: 6,
    daysOffWeeklyTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffWeeklyEn: "The Labour Protection Law",
    daysOffHolidayTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffHolidayEn: "The Labour Protection Law",
    daysAnnualLeaveTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysAnnualLeaveEn: "The Labour Protection Law",
    overtimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    overtimeRateEn: "The Labour Protection Law",
    holidayOvertimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    holidayOvertimeRateEn: "The Labour Protection Law",
    createdAt: new Date("2023-07-18")
  },
  {
    id: "EC-EMP007",
    employeeId: "EMP007",
    typeOfWorkTh: "พนักงานทำความสะอาด",
    typeOfWorkEn: "Cleaning Staff",
    incomePerDay: 380,
    payIncomeDate: 30,
    periodOfEmployment: 12,
    workingHourLimit: 8,
    workingDayPerWeek: 6,
    daysOffWeeklyTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffWeeklyEn: "The Labour Protection Law",
    daysOffHolidayTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffHolidayEn: "The Labour Protection Law",
    daysAnnualLeaveTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysAnnualLeaveEn: "The Labour Protection Law",
    overtimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    overtimeRateEn: "The Labour Protection Law",
    holidayOvertimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    holidayOvertimeRateEn: "The Labour Protection Law",
    createdAt: new Date("2022-12-05")
  },
  {
    id: "EC-EMP008",
    employeeId: "EMP008",
    typeOfWorkTh: "ช่างไม้",
    typeOfWorkEn: "Carpenter",
    incomePerDay: 510,
    payIncomeDate: 30,
    periodOfEmployment: 30,
    workingHourLimit: 8,
    workingDayPerWeek: 5,
    daysOffWeeklyTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffWeeklyEn: "The Labour Protection Law",
    daysOffHolidayTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffHolidayEn: "The Labour Protection Law",
    daysAnnualLeaveTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysAnnualLeaveEn: "The Labour Protection Law",
    overtimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    overtimeRateEn: "The Labour Protection Law",
    holidayOvertimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    holidayOvertimeRateEn: "The Labour Protection Law",
    createdAt: new Date("2023-03-27")
  },
  {
    id: "EC-EMP009",
    employeeId: "EMP009",
    typeOfWorkTh: "พนักงานส่งของ",
    typeOfWorkEn: "Delivery Staff",
    incomePerDay: 470,
    payIncomeDate: 30,
    periodOfEmployment: 21,
    workingHourLimit: 8,
    workingDayPerWeek: 6,
    daysOffWeeklyTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffWeeklyEn: "The Labour Protection Law",
    daysOffHolidayTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffHolidayEn: "The Labour Protection Law",
    daysAnnualLeaveTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysAnnualLeaveEn: "The Labour Protection Law",
    overtimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    overtimeRateEn: "The Labour Protection Law",
    holidayOvertimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    holidayOvertimeRateEn: "The Labour Protection Law",
    createdAt: new Date("2023-06-01")
  },
  {
    id: "EC-EMP010",
    employeeId: "EMP010",
    typeOfWorkTh: "พนักงานบริการหน้าบ้าน",
    typeOfWorkEn: "Front Service Staff",
    incomePerDay: 500,
    payIncomeDate: 30,
    periodOfEmployment: 24,
    workingHourLimit: 8,
    workingDayPerWeek: 6,
    daysOffWeeklyTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffWeeklyEn: "The Labour Protection Law",
    daysOffHolidayTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysOffHolidayEn: "The Labour Protection Law",
    daysAnnualLeaveTh: "ตามกฎหมายคุ้มครองแรงงาน",
    daysAnnualLeaveEn: "The Labour Protection Law",
    overtimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    overtimeRateEn: "The Labour Protection Law",
    holidayOvertimeRateTh: "ตามกฎหมายคุ้มครองแรงงาน",
    holidayOvertimeRateEn: "The Labour Protection Law",
    createdAt: new Date("2023-09-22")
  }
];

export const getMockEmploymentContracts = (): EmploymentContract[] => mockEmploymentContracts;

export const findEmploymentContractsByEmployeeId = (employeeId: string) =>
  mockEmploymentContracts.filter((contract) => contract.employeeId === employeeId);

export const findEmploymentContractById = (id: string) =>
  mockEmploymentContracts.find((contract) => contract.id === id);