import { Employer, TableHeader } from "@/types";

export const employerTableHeaders: TableHeader[] = [
  {
    index: "header-1",
    headerName: "ชื่อ-นามสกุล",
    className: "text-left",
  },
  {
    index: "header-2",
    headerName: "ช่องทางติดต่อ",
    className: "text-left",
  },
  {
    index: "header-4",
    headerName: "สถานะ",
    className: "text-center",
  },
  {
    index: "header-5",
    headerName: "ดำเนินการ",
    className: "text-right",
  },
];

export const mockEmployers: Employer[] = [
  {
    taxId: "0105556123456",
    firstname: "สมชาย",
    lastname: "วิริยะกุล",
    companyName: "บริษัท วัฒนา คอนสตรัคชั่น จำกัด",
    businessType: "ก่อสร้างอาคาร",
    phoneNumber: "0212345678",
    email: "hr@watthana.co.th",
    financialStatusYear: 2024,
    financialStatusIncome: 18500000,
    financialStatusTax: 1250000,
    currentIncome: 1750000,
    currentIncomeDuration: 12,
    addressDetailsTh: "689 ถนนสุขุมวิท",
    addressDetailsEn: "689 Sukhumvit Road",
    districtTh: "วัฒนา",
    districtEn: "Watthana",
    subDistrictTh: "คลองตันเหนือ",
    subDistrictEn: "Khlong Tan Nuea",
    provinceTh: "กรุงเทพมหานคร",
    provinceEn: "Bangkok",
    postalCode: "10110",
    status: "active",
  },
  {
    taxId: "0505559876543",
    firstname: "ชลธิชา",
    lastname: "จิตรมงคล",
    companyName: "นิมมาน โฮสพิทาลิตี้ กรุ๊ป",
    businessType: "โรงแรม/รีสอร์ท",
    phoneNumber: "0539876543",
    email: "hi@nimman.co",
    financialStatusYear: 2024,
    financialStatusIncome: 9200000,
    financialStatusTax: 380000,
    currentIncome: 760000,
    currentIncomeDuration: 12,
    addressDetailsTh: "1 ถนนนิมมานเหมินท์ ซอย 17",
    addressDetailsEn: "1 Nimmanahaeminda Rd., Soi 17",
    districtTh: "เมืองเชียงใหม่",
    districtEn: "Mueang Chiang Mai",
    subDistrictTh: "สุเทพ",
    subDistrictEn: "Suthep",
    provinceTh: "เชียงใหม่",
    provinceEn: "Chiang Mai",
    postalCode: "50200",
    status: "active",
  },
  {
    taxId: "0205551234001",
    firstname: "วรพงศ์",
    lastname: "ศรีราชา",
    companyName: "ศรีราชา โลจิสติกส์ จำกัด",
    businessType: "โลจิสติกส์/คลังสินค้า",
    phoneNumber: "0381234567",
    email: "ops@srlog.co.th",
    financialStatusYear: 2024,
    financialStatusIncome: 14500000,
    financialStatusTax: 650000,
    currentIncome: 980000,
    currentIncomeDuration: 12,
    addressDetailsTh: "55 ถนนสุขุมวิท",
    addressDetailsEn: "55 Sukhumvit Road",
    districtTh: "ศรีราชา",
    districtEn: "Si Racha",
    subDistrictTh: "ศรีราชา",
    subDistrictEn: "Si Racha",
    provinceTh: "ชลบุรี",
    provinceEn: "Chon Buri",
    postalCode: "20110",
    status: "inactive",
  },
  {
    taxId: "0835557654321",
    firstname: "ปรียา",
    lastname: "อัครเดช",
    companyName: "ภูเก็ต ซีฟู้ด โพรเซสซิ่ง",
    businessType: "แปรรูปอาหารทะเล",
    phoneNumber: "0763456789",
    email: "sale@phuketsea.co",
    financialStatusYear: 2024,
    financialStatusIncome: 12800000,
    financialStatusTax: 520000,
    currentIncome: 890000,
    currentIncomeDuration: 12,
    addressDetailsTh: "88 ถนนเทพกระษัตรี",
    addressDetailsEn: "88 Thep Krasattri Road",
    districtTh: "เมืองภูเก็ต",
    districtEn: "Mueang Phuket",
    subDistrictTh: "ตลาดใหญ่",
    subDistrictEn: "Talat Yai",
    provinceTh: "ภูเก็ต",
    provinceEn: "Phuket",
    postalCode: "83000",
    status: "active",
  },
  {
    taxId: "0135557654321",
    firstname: "สุรพล",
    lastname: "อยู่สุข",
    companyName: "อยุธยา แปรรูปอาหาร จำกัด",
    businessType: "โรงงานแปรรูปอาหาร",
    phoneNumber: "0351239990",
    email: "hr@ayuprod.co.th",
    financialStatusYear: 2024,
    financialStatusIncome: 16700000,
    financialStatusTax: 740000,
    currentIncome: 1120000,
    currentIncomeDuration: 12,
    addressDetailsTh: "12/3 ถนนโรจนะ",
    addressDetailsEn: "12/3 Rojana Road",
    districtTh: "บางปะอิน",
    districtEn: "Bang Pa-in",
    subDistrictTh: "บ้านเลน",
    subDistrictEn: "Ban Len",
    provinceTh: "พระนครศรีอยุธยา",
    provinceEn: "Phra Nakhon Si Ayutthaya",
    postalCode: "13160",
    status: "inactive",
  },
  {
    taxId: "0305552468135",
    firstname: "กรกช",
    lastname: "วัฒนากูล",
    companyName: "โคราช โรงงานประกอบชิ้นส่วน",
    businessType: "โรงงานประกอบชิ้นส่วน",
    phoneNumber: "0445552101",
    email: "contact@koratauto.co.th",
    financialStatusYear: 2024,
    financialStatusIncome: 13850000,
    financialStatusTax: 610000,
    currentIncome: 910000,
    currentIncomeDuration: 12,
    addressDetailsTh: "299 ถนนมิตรภาพ",
    addressDetailsEn: "299 Mittraphap Road",
    districtTh: "เมืองนครราชสีมา",
    districtEn: "Mueang Nakhon Ratchasima",
    subDistrictTh: "ในเมือง",
    subDistrictEn: "Nai Mueang",
    provinceTh: "นครราชสีมา",
    provinceEn: "Nakhon Ratchasima",
    postalCode: "30000",
    status: "active",
  },
  {
    taxId: "0745551122334",
    firstname: "ธีรพงศ์",
    lastname: "วงศ์ทวี",
    companyName: "หาดใหญ่ คลีนนิ่ง เซอร์วิส",
    businessType: "บริการทำความสะอาด",
    phoneNumber: "0742223334",
    email: "sales@hatyaitrade.co",
    financialStatusYear: 2024,
    financialStatusIncome: 7200000,
    financialStatusTax: 210000,
    currentIncome: 540000,
    currentIncomeDuration: 12,
    addressDetailsTh: "120 ถนนนิพัทธ์อุทิศ 3",
    addressDetailsEn: "120 Nipat Uthit 3 Road",
    districtTh: "หาดใหญ่",
    districtEn: "Hat Yai",
    subDistrictTh: "หาดใหญ่",
    subDistrictEn: "Hat Yai",
    provinceTh: "สงขลา",
    provinceEn: "Songkhla",
    postalCode: "90110",
    status: "inactive",
  },
  {
    taxId: "0435559988776",
    firstname: "ชญานิษฐ์",
    lastname: "ศิริสุข",
    companyName: "ขอนแก่น ฟู้ด โปรเซสซิ่ง",
    businessType: "โรงงานแปรรูปอาหาร",
    phoneNumber: "0431112223",
    email: "it@kkits.co",
    financialStatusYear: 2024,
    financialStatusIncome: 5600000,
    financialStatusTax: 150000,
    currentIncome: 420000,
    currentIncomeDuration: 12,
    addressDetailsTh: "89 ถนนศรีจันทร์",
    addressDetailsEn: "89 Si Chan Road",
    districtTh: "เมืองขอนแก่น",
    districtEn: "Mueang Khon Kaen",
    subDistrictTh: "ในเมือง",
    subDistrictEn: "Nai Mueang",
    provinceTh: "ขอนแก่น",
    provinceEn: "Khon Kaen",
    postalCode: "40000",
    status: "active",
  },
  {
    taxId: "0385554433221",
    firstname: "ศกลวรรณ",
    lastname: "พงษ์เจริญ",
    companyName: "ระยอง โรงงานยางพารา",
    businessType: "โรงงานยางพารา",
    phoneNumber: "0388887776",
    email: "service@rayongpetro.co.th",
    financialStatusYear: 2024,
    financialStatusIncome: 21200000,
    financialStatusTax: 1320000,
    currentIncome: 1650000,
    currentIncomeDuration: 12,
    addressDetailsTh: "100 ถนนสุขุมวิท",
    addressDetailsEn: "100 Sukhumvit Road",
    districtTh: "เมืองระยอง",
    districtEn: "Mueang Rayong",
    subDistrictTh: "เนินพระ",
    subDistrictEn: "Noen Phra",
    provinceTh: "ระยอง",
    provinceEn: "Rayong",
    postalCode: "21000",
    status: "active",
  },
  {
    taxId: "0535552244668",
    firstname: "ธนกฤต",
    lastname: "ศรีไพศาล",
    companyName: "เชียงราย ฟาร์มแอนด์ฟู้ด",
    businessType: "เกษตร/ฟาร์ม",
    phoneNumber: "0531238885",
    email: "farm@crfood.co",
    financialStatusYear: 2024,
    financialStatusIncome: 4800000,
    financialStatusTax: 120000,
    currentIncome: 350000,
    currentIncomeDuration: 12,
    addressDetailsTh: "77 ถนนพหลโยธิน",
    addressDetailsEn: "77 Phahonyothin Road",
    districtTh: "เมืองเชียงราย",
    districtEn: "Mueang Chiang Rai",
    subDistrictTh: "รอบเวียง",
    subDistrictEn: "Rob Wiang",
    provinceTh: "เชียงราย",
    provinceEn: "Chiang Rai",
    postalCode: "57000",
    status: "inactive",
  },
  {
    taxId: "0755556677882",
    firstname: "จิราพร",
    lastname: "เมธาวงศ์",
    companyName: "นครศรีธรรมราช เมดิแคร์",
    businessType: "สาธารณสุข",
    phoneNumber: "0753334446",
    email: "care@nstmed.co",
    financialStatusYear: 2024,
    financialStatusIncome: 6100000,
    financialStatusTax: 180000,
    currentIncome: 420000,
    currentIncomeDuration: 12,
    addressDetailsTh: "45 ถนนราชดำเนิน",
    addressDetailsEn: "45 Ratchadamnoen Road",
    districtTh: "เมืองนครศรีธรรมราช",
    districtEn: "Mueang Nakhon Si Thammarat",
    subDistrictTh: "ในเมือง",
    subDistrictEn: "Nai Mueang",
    provinceTh: "นครศรีธรรมราช",
    provinceEn: "Nakhon Si Thammarat",
    postalCode: "80000",
    status: "active",
  },
];

export const getEmployers = () => mockEmployers;

export const getEmployerById = (id: string) =>
  mockEmployers.find((employer) => employer.taxId === id);

export const getEmployerFullNameByEmployerId = (id: string) => {
  const employer = getEmployerById(id);

  if (employer) {
    return employer.firstname + " " + employer.lastname;
  }

  return "ไม่พบชื่อนายจ้าง";
};

export const getEmployerFullName = (employer: Employer) =>
  employer.firstname + " " + employer.lastname;

export const getActiveEmployers = () =>
  mockEmployers.filter((employer) => employer.status === "active");

export const countTotalEmployers = (): number => mockEmployers.length;

export const countActiveEmployers = (): number =>
  mockEmployers.filter((employer) => employer.status === "active").length;

export const countInactiveEmployers = (): number =>
  mockEmployers.filter((employer) => employer.status === "inactive").length;
