import { Employee } from '@/types'

export const mockEmployees: Employee[] = [
  {
    id: 1,
    name: "สมชาย วงศ์ใหญ่",
    nationality: "เมียนม่า",
    passportNo: "MA1234567",
    employerName: "บริษัท ABC จำกัด",
    position: "พนักงานทั่วไป",
    workPermitStatus: "active",
    workPermitExpiry: "2024-12-31",
    visaStatus: "active",
    visaExpiry: "2024-11-30",
    healthCheckExpiry: "2024-10-15",
    status: "active",
    registeredDate: "2023-01-15",
  },
  {
    id: 2,
    name: "มานี สุขใส",
    nationality: "ลาว",
    passportNo: "LA9876543",
    employerName: "ร้านอาหาร XYZ",
    position: "พนักงานครัว",
    workPermitStatus: "expiring",
    workPermitExpiry: "2024-01-20",
    visaStatus: "active",
    visaExpiry: "2024-06-15",
    healthCheckExpiry: "2024-03-10",
    status: "active",
    registeredDate: "2023-03-20",
  },
  {
    id: 3,
    name: "สมศรี ดีใจ",
    nationality: "กัมพูชา",
    passportNo: "KH5555555",
    employerName: "โรงงาน DEF",
    position: "พนักงานผลิต",
    workPermitStatus: "expired",
    workPermitExpiry: "2023-12-01",
    visaStatus: "expired",
    visaExpiry: "2023-11-15",
    healthCheckExpiry: "2023-09-30",
    status: "inactive",
    registeredDate: "2022-11-10",
  },
]