import { HighestEducation, WorkPermit } from "@/types";

export const mockWorkPermits: WorkPermit[] = [
    {
        id: "WP-EMP001",
        employeeId: "EMP001",
        typeOfWork: "พนักงานครัว",
        natureOfWork: "เตรียมและปรุงอาหารในร้านอาหาร",
        periodOfEmploymentYear: 2,
        periodOfEmploymentMonth: 0,
        periodOfEmploymentDay: 0,
        employmentValidUntil: new Date("2024-10-15"),
        incomePerDay: 480,
        benefitPerDay: 80,
        highestEducation: HighestEducation.PRIMARY_SCHOOL,
        workExperiences: 3,
        reasonOfNotEmployingThaiPerson: "ต้องการพนักงานที่มีความเข้าใจรสชาติอาหารพม่า",
        createdAt: new Date("2023-10-01")
    },
    {
        id: "WP-EMP002",
        employeeId: "EMP002",
        typeOfWork: "พนักงานบริการ",
        natureOfWork: "ต้อนรับลูกค้าและจัดโต๊ะในร้านอาหาร",
        periodOfEmploymentYear: 1,
        periodOfEmploymentMonth: 6,
        periodOfEmploymentDay: 0,
        employmentValidUntil: new Date("2024-07-30"),
        incomePerDay: 450,
        benefitPerDay: 60,
        highestEducation: HighestEducation.JUNIOR_HIGH_SCHOOL,
        workExperiences: 2,
        reasonOfNotEmployingThaiPerson: "ต้องการบุคลากรที่สามารถสื่อสารภาษาลาวกับลูกค้ากลุ่มหลัก",
        createdAt: new Date("2023-11-12")
    },
    {
        id: "WP-EMP003",
        employeeId: "EMP003",
        typeOfWork: "คนงานผลิต",
        natureOfWork: "คัดแยกและบรรจุสินค้าในโรงงาน",
        periodOfEmploymentYear: 1,
        periodOfEmploymentMonth: 0,
        periodOfEmploymentDay: 15,
        employmentValidUntil: new Date("2023-09-30"),
        incomePerDay: 420,
        benefitPerDay: 50,
        highestEducation: HighestEducation.LOWER_THAN_PRIMARY,
        workExperiences: 4,
        reasonOfNotEmployingThaiPerson: "แรงงานไทยไม่เพียงพอในพื้นที่ห่างไกล",
        createdAt: new Date("2022-08-20")
    },
    {
        id: "WP-EMP004",
        employeeId: "EMP004",
        typeOfWork: "ช่างเทคนิค",
        natureOfWork: "ซ่อมบำรุงเครื่องจักรในโรงงาน",
        periodOfEmploymentYear: 3,
        periodOfEmploymentMonth: 0,
        periodOfEmploymentDay: 0,
        employmentValidUntil: new Date("2024-12-20"),
        incomePerDay: 520,
        benefitPerDay: 90,
        highestEducation: HighestEducation.VOCATIONAL,
        workExperiences: 6,
        reasonOfNotEmployingThaiPerson: "ต้องการผู้เชี่ยวชาญที่มีประสบการณ์เฉพาะทางยาวนาน",
        createdAt: new Date("2023-02-14")
    },
    {
        id: "WP-EMP005",
        employeeId: "EMP005",
        typeOfWork: "คนงานเกษตร",
        natureOfWork: "ดูแลแปลงผักและเก็บเกี่ยวผลผลิต",
        periodOfEmploymentYear: 1,
        periodOfEmploymentMonth: 10,
        periodOfEmploymentDay: 0,
        employmentValidUntil: new Date("2025-01-05"),
        incomePerDay: 400,
        benefitPerDay: 45,
        highestEducation: HighestEducation.PRIMARY_SCHOOL,
        workExperiences: 5,
        reasonOfNotEmployingThaiPerson: "พื้นที่ห่างไกลไม่มีแรงงานไทยทำงานต่อเนื่อง",
        createdAt: new Date("2023-05-09")
    },
    {
        id: "WP-EMP006",
        employeeId: "EMP006",
        typeOfWork: "พนักงานคลังสินค้า",
        natureOfWork: "จัดเรียงสินค้าในคลังและควบคุมสต็อก",
        periodOfEmploymentYear: 2,
        periodOfEmploymentMonth: 3,
        periodOfEmploymentDay: 0,
        employmentValidUntil: new Date("2024-11-30"),
        incomePerDay: 430,
        benefitPerDay: 60,
        highestEducation: HighestEducation.JUNIOR_HIGH_SCHOOL,
        workExperiences: 3,
        reasonOfNotEmployingThaiPerson: "ต้องการพนักงานที่สามารถทำงานเป็นกะต่อเนื่อง",
        createdAt: new Date("2023-07-18")
    },
    {
        id: "WP-EMP007",
        employeeId: "EMP007",
        typeOfWork: "พนักงานทำความสะอาด",
        natureOfWork: "ดูแลความสะอาดโรงแรมและพื้นที่ส่วนกลาง",
        periodOfEmploymentYear: 1,
        periodOfEmploymentMonth: 0,
        periodOfEmploymentDay: 0,
        employmentValidUntil: new Date("2024-04-30"),
        incomePerDay: 380,
        benefitPerDay: 40,
        highestEducation: HighestEducation.NO_FORMAL_EDUCATION,
        workExperiences: 2,
        reasonOfNotEmployingThaiPerson: "แรงงานไทยไม่เพียงพอในช่วงฤดูกาลท่องเที่ยว",
        createdAt: new Date("2022-12-05")
    },
    {
        id: "WP-EMP008",
        employeeId: "EMP008",
        typeOfWork: "ช่างไม้",
        natureOfWork: "ประกอบและติดตั้งเฟอร์นิเจอร์ในโรงงาน",
        periodOfEmploymentYear: 2,
        periodOfEmploymentMonth: 6,
        periodOfEmploymentDay: 0,
        employmentValidUntil: new Date("2025-02-20"),
        incomePerDay: 510,
        benefitPerDay: 85,
        highestEducation: HighestEducation.VOCATIONAL,
        workExperiences: 7,
        reasonOfNotEmployingThaiPerson: "ต้องการผู้ชำนาญงานไม้แบบดั้งเดิมจากลาว",
        createdAt: new Date("2023-03-27")
    },
    {
        id: "WP-EMP009",
        employeeId: "EMP009",
        typeOfWork: "พนักงานส่งของ",
        natureOfWork: "จัดส่งสินค้าในเขตกรุงเทพมหานคร",
        periodOfEmploymentYear: 1,
        periodOfEmploymentMonth: 9,
        periodOfEmploymentDay: 0,
        employmentValidUntil: new Date("2024-12-25"),
        incomePerDay: 470,
        benefitPerDay: 70,
        highestEducation: HighestEducation.SENIOR_HIGH_SCHOOL,
        workExperiences: 4,
        reasonOfNotEmployingThaiPerson: "งานต้องใช้ภาษาเขมรในการสื่อสารกับลูกค้าต่างด้าว",
        createdAt: new Date("2023-06-01")
    },
    {
        id: "WP-EMP010",
        employeeId: "EMP010",
        typeOfWork: "พนักงานบริการหน้าบ้าน",
        natureOfWork: "ดูแลลูกค้าและจัดเตรียมเครื่องดื่มในรีสอร์ท",
        periodOfEmploymentYear: 2,
        periodOfEmploymentMonth: 0,
        periodOfEmploymentDay: 0,
        employmentValidUntil: new Date("2025-01-15"),
        incomePerDay: 500,
        benefitPerDay: 75,
        highestEducation: HighestEducation.SENIOR_HIGH_SCHOOL,
        workExperiences: 5,
        reasonOfNotEmployingThaiPerson: "ต้องการบุคลากรที่สื่อสารภาษาพม่ากับลูกค้าชาวพม่าได้",
        createdAt: new Date("2023-09-22")
    }
];

export const getMockWorkPermits = (): WorkPermit[] => mockWorkPermits;

export const findMockWorkPermitsByEmployeeId = (employeeId: string) =>
    mockWorkPermits.filter((permit) => permit.employeeId === employeeId);