import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ConditionalSidebar } from "@/components/layout/ConditionalSidebar";
import { cookies } from "next/headers";

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value == "true";

  return (
    <html lang="en">
      <body
        className={`${kanit.variable} antialiased`}
      >
        <SidebarProvider defaultOpen={defaultOpen}>
            <ConditionalSidebar>{children}</ConditionalSidebar>
        </SidebarProvider>
      </body>
    </html>
  );
}
